// Référentiel plan comptable Käfer PME suisse — code → libellé
// Extrait automatiquement de scripts/ingest-kafer.ts pour enrichir les réponses API
// (source unique : ingest-kafer.ts ACCOUNTS tableau)

export const KAFER_LABELS: Record<string, string> = {
  "1000": "Caisse",
  "1020": "Banque — compte courant",
  "1021": "Compte de virement postal",
  "1060": "Titres et placements financiers à court terme",
  "1100": "Créances clients (débiteurs)",
  "1109": "Ducroire",
  "1170": "Impôt préalable TVA (biens et services)",
  "1171": "Impôt préalable TVA (investissements)",
  "1200": "Stock de marchandises",
  "1210": "Stock de matières premières",
  "1280": "Travaux en cours",
  "1300": "Actifs de régularisation",
  "1400": "Immobilisations financières",
  "1500": "Machines et appareils",
  "1510": "Mobilier et installations d'exploitation",
  "1520": "Matériel informatique (hardware)",
  "1521": "Logiciels et licences",
  "1530": "Véhicules d'entreprise",
  "1600": "Immeubles d'exploitation",
  "1700": "Droits et immobilisations incorporelles",
  "2000": "Créanciers fournisseurs",
  "2030": "Acomptes de clients",
  "2100": "Dettes bancaires à court terme",
  "2200": "TVA due (décompte AFC)",
  "2201": "Décompte TVA — compte courant AFC",
  "2206": "Acomptes reçus pour TVA",
  "2270": "Impôts directs dus (IFD, ICC)",
  "2300": "Emprunts à long terme",
  "2400": "Passifs de régularisation",
  "2600": "Provisions",
  "2800": "Capital social (capital-actions / parts Sàrl)",
  "2900": "Réserves générales légales",
  "2950": "Réserves libres / facultatives",
  "2970": "Bénéfice (perte) reporté",
  "2979": "Bénéfice (perte) de l'exercice",
  "3000": "Ventes de marchandises",
  "3200": "Prestations de services",
  "3400": "Autres produits d'exploitation",
  "3800": "Rabais et escomptes accordés",
  "4000": "Achats de marchandises destinées à la revente",
  "4200": "Charges de sous-traitance / prestations de tiers",
  "4400": "Variation de stocks",
  "4900": "Frais d'achat / frais accessoires",
  "5000": "Salaires",
  "5700": "Charges sociales AVS/AI/APG/AC/AM",
  "5710": "Prestations LPP (2ème pilier)",
  "5720": "Assurance accident LAA",
  "5800": "Autres charges de personnel",
  "6000": "Loyers",
  "6100": "Entretien, réparation, remplacement",
  "6200": "Primes d'assurance choses",
  "6300": "Énergie, eau, gaz, chauffage",
  "6400": "Frais de télécommunication",
  "6500": "Frais administratifs (fournitures, abonnements)",
  "6510": "Honoraires fiduciaires / conseillers",
  "6600": "Publicité et relations publiques",
  "6640": "Frais de repas et représentation",
  "6700": "Amortissements",
  "6800": "Charges financières (intérêts et frais bancaires)",
  "7000": "Produits accessoires",
  "7500": "Produits financiers (intérêts bancaires perçus)",
  "7900": "Produits immobiliers (loyers reçus)",
  "8000": "Charges extraordinaires / uniques",
  "8100": "Produits extraordinaires / uniques",
  "9000": "Compte de résultat",
  "9100": "Bilan",
};

/** Retourne le libellé Käfer si connu, sinon le code lui-même en fallback. */
export function kaferLabel(code: string): string {
  return KAFER_LABELS[code] ?? code;
}
